env:
  browser: true
  es2021: true
  jest/globals: true
extends: airbnb-base
plugins: ["jest"]
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
    "no-console": "off",
    "import/extensions":"off",
    "no-unused-expressions":"off"
}
